# Copyright Red Hat
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: compute-operator
spec:
  reference:
    workspace:
      path: root:{{ .Organization }}
      exportName: compute-apis
