apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  clusterName: root:rh-sso-13066380:itdove
  name: compute-apis
spec:
  latestResourceSchemas:
  - today-2022-06-16.registeredclusters.singapore.open-cluster-management.io