apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compute-operator-manager-role
rules:
- apiGroups: ["apis.kcp.dev"]
  resources: ["apiexports"]
  verbs: ["get", "list"]
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports/content
  resourceNames:
  - compute-apis
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
