# Copyright Red Hat

apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-operator-manager
  namespace: {{ .Namespace }}
  labels:
    control-plane: compute-operator-manager
spec:
  selector:
    matchLabels:
      control-plane: compute-operator-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: compute-operator-manager
        cluster-antiaffinity-selector: compute-operator-controller
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: cluster-antiaffinity-selector
                      operator: In
                      values:
                        - compute-operator-controller
                topologyKey: topology.kubernetes.io/zone
              weight: 70
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: cluster-antiaffinity-selector
                      operator: In
                      values:
                        - compute-operator-controller
                topologyKey: kubernetes.io/hostname
              weight: 35
      containers:
        - args:
            - manager
            - --enable-leader-election
            - "--health-probe-bind-address=:8081"
            - "--v=6"
          image: {{ .Image }}
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          name: manager
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 50Mi
      serviceAccountName: compute-operator-manager
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
        - key: dedicated
          operator: Exists
          effect: NoSchedule
