# Copyright Red Hat
# Run `make samples` if you modified the original file in the resources/compute-templates  
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: compute-operator
spec:
  reference:
    workspace:
      path: root:{{ .Organization }}
      exportName: compute-apis
